/**
 * Persian names for the EAR classification lists.
 *
 * The English name remains the canonical lookup key into the rate tables —
 * nothing here is ever used to find a rate. These are display labels only, and
 * each carries its EAR reference code so the English wording stays findable in
 * the Swiss Re Rating Guide.
 *
 * Authored against common Iranian insurance/engineering usage. If a term reads
 * wrong to an underwriter, correct it here: the rate is unaffected.
 */

/** `<code> — <Persian>`, e.g. `12.5 — کارخانه رنگ‌سازی…`. */
export function withCode(code: string, fa: string): string {
  return code ? `${code} — ${fa}` : fa
}

/** Sub-group English name → EAR code + Persian name. */
export const SUBGROUP_FA: Record<string, { code: string; fa: string }> = {
  '01.1.1 Boilerhouse installations — natural circulation, ≤250 t/h (boiler + superheaters, fans, water treatment, feed pumps)': { code: '01.1.1', fa: 'دیگ‌خانه — گردش طبیعی، تا ۲۵۰ تن بر ساعت (دیگ بخار، سوپرهیتر، فن، تصفیهٔ آب، پمپ تغذیه)' },
  '01.1.1 Boilerhouse installations comprising boiler with all auxiliaries (superheaters, fans, feed pumps, water treatment) - natural circulat': { code: '01.1.1', fa: 'دیگ‌خانه با تمام تجهیزات جانبی (سوپرهیتر، فن، پمپ تغذیه، تصفیهٔ آب) — گردش طبیعی' },
  '01.1.2 Turbogenerating sets — turbine, generator, cooling system, governor, directly connected auxiliaries — up to 50 MW': { code: '01.1.2', fa: 'مجموعهٔ توربوژنراتور بخار (توربین، ژنراتور، خنک‌کاری، گاورنر و تجهیزات جانبی متصل) — تا ۵۰ مگاوات' },
  '01.1.2 Turbogenerating sets (turbine, generator, cooling system, governor, directly connected auxiliaries) — 50 to 125 MW': { code: '01.1.2', fa: 'مجموعهٔ توربوژنراتور بخار (توربین، ژنراتور، خنک‌کاری، گاورنر و تجهیزات جانبی) — ۵۰ تا ۱۲۵ مگاوات' },
  '01.1.2 Turbogenerating sets (turbine, generator, cooling system, governor, directly connected auxiliaries) — 125 to 250 MW': { code: '01.1.2', fa: 'مجموعهٔ توربوژنراتور بخار (توربین، ژنراتور، خنک‌کاری، گاورنر و تجهیزات جانبی) — ۱۲۵ تا ۲۵۰ مگاوات' },
  '01.1.2 Turbogenerating sets (turbine, generator, cooling system, governor, directly connected auxiliaries) — 250 to 450 MW': { code: '01.1.2', fa: 'مجموعهٔ توربوژنراتور بخار (توربین، ژنراتور، خنک‌کاری، گاورنر و تجهیزات جانبی) — ۲۵۰ تا ۴۵۰ مگاوات' },
  '01.1.3 Water-systems cycle comprising condenser, feed heater piping, pumps etc.': { code: '01.1.3', fa: 'چرخهٔ آب و بخار شامل کندانسور، لوله‌کشی گرم‌کن تغذیه، پمپ‌ها و مانند آن' },
  '01.1.4 Electric equipment, control and measuring installations incl. station transformers': { code: '01.1.4', fa: 'تجهیزات برقی، ابزار دقیق و کنترل، به‌همراه ترانسفورماتورهای نیروگاه' },
  '01.1.5 Balance of plant comprising: ash-handling, off-site tanks': { code: '01.1.5', fa: 'تجهیزات جانبی نیروگاه شامل خاکستربرداری و مخازن بیرون از محوطه' },
  '01.2.1 Gas turbine power plants — Gasturbo generating sets (turbine, compressor, generator, starting device, all auxiliaries) — up to 10 MW': { code: '01.2.1', fa: 'نیروگاه توربین گازی — مجموعهٔ توربوژنراتور گازی (توربین، کمپرسور، ژنراتور، راه‌انداز و تجهیزات جانبی) — تا ۱۰ مگاوات' },
  '01.2.1 Gasturbo generating sets (turbine, compressor, generator, starting device, all auxiliaries connected to foundation block) — 10 to 20': { code: '01.2.1', fa: 'مجموعهٔ توربوژنراتور گازی (توربین، کمپرسور، ژنراتور، راه‌انداز و تجهیزات جانبی روی فونداسیون) — ۱۰ تا ۲۰ مگاوات' },
  '01.2.1 Gasturbo generating sets (turbine, compressor, generator, starting device, all auxiliaries connected to foundation block) — 20 to 40': { code: '01.2.1', fa: 'مجموعهٔ توربوژنراتور گازی (توربین، کمپرسور، ژنراتور، راه‌انداز و تجهیزات جانبی روی فونداسیون) — ۲۰ تا ۴۰ مگاوات' },
  '01.2.2 Electrical equipment control/measuring: air inlet/outlet, filters, piping, pumps incl. station transformers': { code: '01.2.2', fa: 'تجهیزات برقی، کنترل و ابزار دقیق: ورودی/خروجی هوا، فیلتر، لوله‌کشی، پمپ و ترانسفورماتورهای نیروگاه' },
  '01.2.3 Balance of plant off-site installations: tanks, gas receiving and/or pressure reducing plant etc.': { code: '01.2.3', fa: 'تأسیسات بیرون از محوطه: مخازن، ایستگاه دریافت گاز و/یا کاهش فشار' },
  '01.3.1 Diesel generator sets — diesel engine, starting device, generator and all auxiliaries attached — engines with speed above 500 rpm': { code: '01.3.1', fa: 'مجموعهٔ دیزل ژنراتور (موتور دیزل، راه‌انداز، ژنراتور و تجهیزات جانبی متصل) — دور بالای ۵۰۰ دور بر دقیقه' },
  '01.3.1 Diesel Generator sets (diesel engine, starting device, generator, all attached auxiliaries) - engines with speed above 500 rpm — engi': { code: '01.3.1', fa: 'مجموعهٔ دیزل ژنراتور (موتور دیزل، راه‌انداز، ژنراتور و تجهیزات جانبی متصل) — دور بالای ۵۰۰ دور بر دقیقه (ردیف دوم جدول)' },
  '01.3.2 Electrical equipment control/measuring; air inlet/outlet, filters, piping, pumps': { code: '01.3.2', fa: 'تجهیزات برقی، کنترل و ابزار دقیق؛ ورودی/خروجی هوا، فیلتر، لوله‌کشی و پمپ' },
  '01.3.3 Balance of plant comprising off-site installations, tanks, etc.': { code: '01.3.3', fa: 'تجهیزات جانبی شامل تأسیسات بیرون از محوطه، مخازن و مانند آن' },
  '01.4.1 Turbinehouse installations - Pelton turbine, up to 100 MW': { code: '01.4.1', fa: 'تأسیسات توربین‌خانهٔ برق‌آبی — توربین پلتون، تا ۱۰۰ مگاوات' },
  '01.4.1 Turbinehouse installations - Pelton turbine — Pelton, 100 to 200 MW': { code: '01.4.1', fa: 'تأسیسات توربین‌خانهٔ برق‌آبی — توربین پلتون، ۱۰۰ تا ۲۰۰ مگاوات' },
  '01.4.1 Turbinehouse installations - Pelton turbine — Francis turbine, up to 100 MW': { code: '01.4.1', fa: 'تأسیسات توربین‌خانهٔ برق‌آبی — توربین فرانسیس، تا ۱۰۰ مگاوات' },
  '01.4.1 Turbinehouse installations - Pelton turbine — Francis, 100 to 200 MW': { code: '01.4.1', fa: 'تأسیسات توربین‌خانهٔ برق‌آبی — توربین فرانسیس، ۱۰۰ تا ۲۰۰ مگاوات' },
  '01.4.1 Turbinehouse installations - Pelton turbine — Kaplan turbine, up to 100 MW': { code: '01.4.1', fa: 'تأسیسات توربین‌خانهٔ برق‌آبی — توربین کاپلان، تا ۱۰۰ مگاوات' },
  '01.4.1 Turbinehouse installations - Pelton turbine — Kaplan, 100 to 200 MW': { code: '01.4.1', fa: 'تأسیسات توربین‌خانهٔ برق‌آبی — توربین کاپلان، ۱۰۰ تا ۲۰۰ مگاوات' },
  '01.4.1 Turbinehouse installations - Pelton turbine — Other types (tubular/axial flow reaction turbines), up to 25 MW': { code: '01.4.1', fa: 'تأسیسات توربین‌خانهٔ برق‌آبی — سایر انواع (توربین‌های عکس‌العملی محوری/لوله‌ای)، تا ۲۵ مگاوات' },
  '01.4.1 Turbinehouse installations - Pelton turbine — Other types, 25 to 50 MW': { code: '01.4.1', fa: 'تأسیسات توربین‌خانهٔ برق‌آبی — سایر انواع، ۲۵ تا ۵۰ مگاوات' },
  '01.4.2 Pumping house installations - Horizontal pumping sets, up to 25 MW': { code: '01.4.2', fa: 'تأسیسات ایستگاه پمپاژ — مجموعهٔ پمپ افقی، تا ۲۵ مگاوات' },
  '01.4.2 Pumping house installations - Horizontal pumping sets — Horizontal, 25 to 50 MW': { code: '01.4.2', fa: 'تأسیسات ایستگاه پمپاژ — مجموعهٔ پمپ افقی، ۲۵ تا ۵۰ مگاوات' },
  '01.4.2 Pumping house installations - Horizontal pumping sets — Vertical pumping sets, up to 25 MW': { code: '01.4.2', fa: 'تأسیسات ایستگاه پمپاژ — مجموعهٔ پمپ عمودی، تا ۲۵ مگاوات' },
  '01.4.2 Pumping house installations - Horizontal pumping sets — Vertical, 25 to 50 MW': { code: '01.4.2', fa: 'تأسیسات ایستگاه پمپاژ — مجموعهٔ پمپ عمودی، ۲۵ تا ۵۰ مگاوات' },
  '01.4.3 Electrical equipment and measuring installations, station transformers, pressurised air control systems, etc.': { code: '01.4.3', fa: 'تجهیزات برقی و ابزار دقیق، ترانسفورماتورهای نیروگاه، سامانه‌های کنترل هوای فشرده و مانند آن' },
  '01.4.4 Water intake and off-site installations: penstocks, gates, trash racks, weir installations and the like': { code: '01.4.4', fa: 'آبگیر و تأسیسات بیرون از محوطه: پن‌استاک، دریچه‌ها، آشغال‌گیر، سرریز و مانند آن' },
  '01.5.1 Transformer stations — power transformer, phase compensators, cooling control, capacitors, rectifier banks — 30 to 150 MVA': { code: '01.5.1', fa: 'پست‌های ترانسفورماتور (ترانسفورماتور قدرت، جبران‌ساز فاز، کنترل خنک‌کاری، خازن، یکسوساز) — ۳۰ تا ۱۵۰ مگاولت‌آمپر' },
  '01.5.1 Transformer stations — power transformer, phase compensators, cooling control, capacitors, rectifier banks — 150 to 300 MVA': { code: '01.5.1', fa: 'پست‌های ترانسفورماتور (ترانسفورماتور قدرت، جبران‌ساز فاز، کنترل خنک‌کاری، خازن، یکسوساز) — ۱۵۰ تا ۳۰۰ مگاولت‌آمپر' },
  '01.5.1 Transformer stations — power transformer, phase compensators, cooling control, capacitors, rectifier banks — above 300 MVA': { code: '01.5.1', fa: 'پست‌های ترانسفورماتور (ترانسفورماتور قدرت، جبران‌ساز فاز، کنترل خنک‌کاری، خازن، یکسوساز) — بالای ۳۰۰ مگاولت‌آمپر' },
  '01.5.1 Transformer Stations (power transformer, phase compensators, cooling/control/protection auxiliaries, capacitors, rectifier banks) - P': { code: '01.5.1', fa: 'پست‌های ترانسفورماتور (ترانسفورماتور قدرت، جبران‌ساز فاز، تجهیزات جانبی خنک‌کاری/کنترل/حفاظت، خازن، یکسوساز)' },
  '01.5.2 Switchgear installations (circuit breakers, control/protection equipment, line feeders) up to 60 kV': { code: '01.5.2', fa: 'تأسیسات کلیدخانه (کلید قدرت، تجهیزات کنترل/حفاظت، فیدرهای خط) — تا ۶۰ کیلوولت' },
  '01.5.2 Switchgear installations (circuit breakers, control/protection equipment, line feeders) — 60 kV to 500 kV': { code: '01.5.2', fa: 'تأسیسات کلیدخانه (کلید قدرت، تجهیزات کنترل/حفاظت، فیدرهای خط) — ۶۰ تا ۵۰۰ کیلوولت' },
  '01.5.2 Switchgear installations (circuit breakers, control/protection equipment, line feeders) — above 500 kV': { code: '01.5.2', fa: 'تأسیسات کلیدخانه (کلید قدرت، تجهیزات کنترل/حفاظت، فیدرهای خط) — بالای ۵۰۰ کیلوولت' },
  '01.5.3 Overhead transmission lines incl. tower, insulators, etc. up to 60 kV': { code: '01.5.3', fa: 'خطوط انتقال هوایی شامل دکل، مقره و مانند آن — تا ۶۰ کیلوولت' },
  '01.5.3 Overhead transmission lines incl. tower, insulators, etc. — 60 kV to 220 kV': { code: '01.5.3', fa: 'خطوط انتقال هوایی شامل دکل، مقره و مانند آن — ۶۰ تا ۲۲۰ کیلوولت' },
  '01.5.3 Overhead transmission lines incl. tower, insulators, etc. — 220 kV to 750 kV': { code: '01.5.3', fa: 'خطوط انتقال هوایی شامل دکل، مقره و مانند آن — ۲۲۰ تا ۷۵۰ کیلوولت' },
  '01.5.4 Underground cables incl. all auxiliaries but excl. civil works - Classical insulated and oil filled cables': { code: '01.5.4', fa: 'کابل‌های زمینی با تمام تجهیزات جانبی، بدون کارهای عمرانی — کابل‌های با عایق کلاسیک و روغنی' },
  '01.5.4 Underground cables incl. all auxiliaries but excl. civil works - Classical insulated and oil filled cables — Gas filled cables and al': { code: '01.5.4', fa: 'کابل‌های زمینی با تمام تجهیزات جانبی، بدون کارهای عمرانی — کابل‌های گازی و مشابه' },
  '01.6.1 Waterworks, water purification installations (baths, sewers, desalination; public utilities)': { code: '01.6.1', fa: 'تأسیسات آبرسانی و تصفیهٔ آب (استخر، فاضلاب‌رو، آب‌شیرین‌کن؛ خدمات عمومی)' },
  '01.6.2 Desalination plants (excl. power plants, seawater/treated-water pumping stations) - Thermal processes: MSF/VTE/HFF': { code: '01.6.2', fa: 'تأسیسات آب‌شیرین‌کن (بدون نیروگاه و ایستگاه پمپاژ) — فرآیندهای حرارتی MSF/VTE/HFF' },
  '01.6.2 Desalination plants (excl. power plants, seawater/treated-water pumping stations) - Thermal processes: MSF/VTE/HFF — Mechanical/elect': { code: '01.6.2', fa: 'تأسیسات آب‌شیرین‌کن (بدون نیروگاه و ایستگاه پمپاژ) — فرآیندهای مکانیکی/الکتریکی (اسمز معکوس)' },
  '01.6.3 Sewage effluent treatment plants complete, mainly pumps/conveyors/filters/pipes etc. but excl. civil works': { code: '01.6.3', fa: 'تصفیه‌خانهٔ کامل فاضلاب، عمدتاً پمپ، نوار نقاله، فیلتر و لوله‌کشی، بدون کارهای عمرانی' },
  '01.6.4 Off-site installations: well installations, main/booster water pumps, storage tanks but excl. civil works (trenching)': { code: '01.6.4', fa: 'تأسیسات بیرون از محوطه: چاه، پمپ اصلی و بوستر، مخازن ذخیره، بدون کارهای عمرانی (ترانشه‌زنی)' },
  '01.7.1 Incineration and district heating plants complete but excl. turbine generating sets': { code: '01.7.1', fa: 'تأسیسات زباله‌سوز و گرمایش منطقه‌ای، بدون مجموعهٔ توربوژنراتور' },
  '01.7.2 Composting plants mainly comprising mills, cranes, mixers, conveyors, fermentation tanks, etc.': { code: '01.7.2', fa: 'تأسیسات کمپوست شامل آسیاب، جرثقیل، میکسر، نوار نقاله و مخازن تخمیر' },
  '01.7.3 Scrap handling (shredder) plants': { code: '01.7.3', fa: 'تأسیسات بازیافت و خردایش ضایعات فلزی (شردر)' },
  '01.8.1 Radio and television installations (transmitters, relaying stations, re-broadcasting transmitters, antennas; public utilities)': { code: '01.8.1', fa: 'تأسیسات رادیو و تلویزیون (فرستنده، ایستگاه رله، بازپخش، آنتن؛ خدمات عمومی)' },
  '01.8.2 Telephone installations - Exchange equipment, control units etc., short-wave transmitters and receivers': { code: '01.8.2', fa: 'تأسیسات مخابرات تلفنی — تجهیزات مرکز تلفن، واحدهای کنترل، فرستنده و گیرندهٔ موج کوتاه' },
  '01.8.2 Telephone installations - Exchange equipment, control units etc., short-wave transmitters and receivers — Telephone networks (cabling': { code: '01.8.2', fa: 'تأسیسات مخابرات تلفنی — شبکهٔ تلفن (کابل‌کشی)' },
  '01.8.2 Telephone installations - Exchange equipment, control units etc., short-wave transmitters and receivers — Telephone networks: undergr': { code: '01.8.2', fa: 'تأسیسات مخابرات تلفنی — شبکهٔ تلفن زمینی' },
  '01.8.2 Telephone installations - Exchange equipment, control units etc., short-wave transmitters and receivers — Telephone networks: special': { code: '01.8.2', fa: 'تأسیسات مخابرات تلفنی — شبکهٔ تلفن با کاربری خاص' },
  '02.1 Boilers, steam generation installations — incl. all auxiliaries, ≤250 t/h': { code: '02.1', fa: 'دیگ بخار و تأسیسات تولید بخار با تمام تجهیزات جانبی — تا ۲۵۰ تن بر ساعت' },
  '02.2 Steam turbine generating sets, complete incl. water steam cycle, control/measuring equipment - up to 25 MW': { code: '02.2', fa: 'مجموعهٔ توربوژنراتور بخار کامل شامل چرخهٔ آب و بخار و تجهیزات کنترل/ابزار دقیق — تا ۲۵ مگاوات' },
  '02.2 Steam turbine generating sets, complete incl. water steam cycle, control/measuring equipment — 25 to 50 MW': { code: '02.2', fa: 'مجموعهٔ توربوژنراتور بخار کامل شامل چرخهٔ آب و بخار و تجهیزات کنترل/ابزار دقیق — ۲۵ تا ۵۰ مگاوات' },
  '02.3 Gas turbine sets incl. all auxiliaries - up to 10 MW': { code: '02.3', fa: 'مجموعهٔ توربین گازی با تمام تجهیزات جانبی — تا ۱۰ مگاوات' },
  '02.3 Gas turbine sets incl. all auxiliaries — 10 MW to 25 MW': { code: '02.3', fa: 'مجموعهٔ توربین گازی با تمام تجهیزات جانبی — ۱۰ تا ۲۵ مگاوات' },
  '02.4 Diesel generating sets complete up to 25 MW': { code: '02.4', fa: 'مجموعهٔ دیزل ژنراتور کامل — تا ۲۵ مگاوات' },
  '02.5 Electrical installations, sub-stations, transformers, switchyard and the like': { code: '02.5', fa: 'تأسیسات برقی، پست‌های فرعی، ترانسفورماتور، محوطهٔ کلید و مانند آن' },
  '02.6 Water supply installations, mainly pumps, valves and piping but excl. civil works/trenching': { code: '02.6', fa: 'تأسیسات آبرسانی، عمدتاً پمپ، شیرآلات و لوله‌کشی، بدون کارهای عمرانی/ترانشه‌زنی' },
  '02.7 Plant compressed air supply installations (utilities in industrial plants)': { code: '02.7', fa: 'تأسیسات تأمین هوای فشردهٔ کارخانه' },
  '02.8 Air conditioning complete: compressor, air conditioners, humidifiers, heater, ozonizer and conduits': { code: '02.8', fa: 'تهویهٔ مطبوع کامل: کمپرسور، هواساز، رطوبت‌زن، گرم‌کن، ازن‌ساز و کانال‌کشی' },
  '02.9 Gas installations, mainly receiving station, de-compression devices, scrubbers, pipe works and the like': { code: '02.9', fa: 'تأسیسات گاز، عمدتاً ایستگاه دریافت، تجهیزات کاهش فشار، اسکرابر و لوله‌کشی' },
  '02.10 Environment protection plants, mainly waste water/effluent treatment and air/gas filter installations': { code: '02.10', fa: 'تأسیسات حفاظت محیط زیست، عمدتاً تصفیهٔ پساب و فیلتراسیون هوا/گاز' },
  '03.1 Underground mining installations (mainly conveyors, hoists, ventilating, pumping devices)': { code: '03.1', fa: 'تأسیسات معدن‌کاری زیرزمینی (عمدتاً نوار نقاله، بالابر، تهویه و پمپاژ)' },
  '03.2 Dredgers, production machines (mining industry)': { code: '03.2', fa: 'لایروب و ماشین‌آلات استخراج (صنعت معدن)' },
  '03.3 Open cut mining installations — incl. ore improving and loading facilities (breakers, crushers, mills, conveyors, weighing, washing equipment)': { code: '03.3', fa: 'تأسیسات معدن‌کاری روباز — شامل تجهیزات فرآوری و بارگیری سنگ معدن (سنگ‌شکن، آسیاب، نوار نقاله، توزین، شست‌وشو)' },
  '03.4 Ore pre-processing installations of non-ferrous products, alumina (excl. electrolysis) copper, tin and comparable installations; kilns,': { code: '03.4', fa: 'تأسیسات پیش‌فرآوری سنگ معدن فلزات غیرآهنی، آلومینا (بدون الکترولیز)، مس، قلع و مشابه؛ کوره‌ها' },
  '04.3.1 Simple classical refinery processes (atmospheric/vacuum distillation, hydrodesulph., residue conversion)': { code: '04.3.1', fa: 'فرآیندهای سادهٔ پالایشگاهی (تقطیر اتمسفری/خلأ، گوگردزدایی هیدروژنی، تبدیل باقی‌مانده)' },
  '04.3.2 More sophisticated refinery processes (distillate hydro-treating, hydro-cracking, methane steam reforming, pyrolysis)': { code: '04.3.2', fa: 'فرآیندهای پیشرفتهٔ پالایشگاهی (هیدروتریتینگ، هیدروکراکینگ، ریفرمینگ بخار متان، پیرولیز)' },
  '04.3.3 Lubrificating oil plants': { code: '04.3.3', fa: 'واحد تولید روغن روان‌کننده' },
  '04.3.4 Installation for recovery of non hydro-carbon by-products (sulphur, hydrogen, carbons, acids)': { code: '04.3.4', fa: 'واحد بازیافت محصولات جانبی غیرهیدروکربنی (گوگرد، هیدروژن، کربن، اسیدها)' },
  '04.3.6 Auxiliary equipment such as: piping, effluent plant, water treatment, structures and the like but excluding storage tanks (storage ta': { code: '04.3.6', fa: 'تجهیزات جانبی مانند لوله‌کشی، واحد پساب، تصفیهٔ آب و سازه‌ها، بدون مخازن ذخیره' },
  '04.4.1 Acid plants and comparable risks such as: sulphuric acid, nitric acid, hydrochloric acid and chloride electrolysis plants and the lik': { code: '04.4.1', fa: 'واحد تولید اسید و ریسک‌های مشابه: اسید سولفوریک، نیتریک، کلریدریک و الکترولیز کلر' },
  '04.4.2 Air liquifaction and fractioning plants': { code: '04.4.2', fa: 'واحد مایع‌سازی و تفکیک هوا' },
  '04.4.3 Processes for the production of basic material for mineral pigments, colouring substances and the like': { code: '04.4.3', fa: 'فرآیند تولید مواد اولیهٔ رنگدانه‌های معدنی و مواد رنگ‌زا' },
  '04.4.4 Processes for the production of basic pharmaceutical substances and comparable basic material': { code: '04.4.4', fa: 'فرآیند تولید مواد اولیهٔ دارویی و مواد پایهٔ مشابه' },
  '04.4.5 Auxiliary equipment such as piping, lab. equipment, effluent plant and the like': { code: '04.4.5', fa: 'تجهیزات جانبی مانند لوله‌کشی، تجهیزات آزمایشگاهی و واحد پساب' },
  '04.5.3 Phosphate fertilizer plants, super-phosphate': { code: '04.5.3', fa: 'واحد تولید کود فسفاته و سوپرفسفات' },
  '04.5.4 Fertilizer plants — potash (chemical industry)': { code: '04.5.4', fa: 'واحد تولید کود پتاسه (صنایع شیمیایی)' },
  '04.5.5 Multi-nutritive-substance fertilizers, i.e. mixing of N-P-K products': { code: '04.5.5', fa: 'واحد تولید کود مرکب چندمغذی (اختلاط محصولات N-P-K)' },
  '04.5.6 Auxiliaries such as piping, effluent plant, cabling and the like': { code: '04.5.6', fa: 'تجهیزات جانبی مانند لوله‌کشی، واحد پساب و کابل‌کشی' },
  '04.6.1 Storage, transport and loading facilities — tank farms (incl. piping, pumps and measuring equipment; excl. civil works)': { code: '04.6.1', fa: 'تأسیسات ذخیره، انتقال و بارگیری — مخازن ذخیره (شامل لوله‌کشی، پمپ و ابزار توزین؛ بدون کارهای عمرانی)' },
  '04.6.3 Pumping and compressor stations in pipelines incl. auxiliaries - turbine driven': { code: '04.6.3', fa: 'ایستگاه پمپاژ و تقویت فشار خطوط لوله با تجهیزات جانبی — محرک توربینی' },
  '04.6.3 Pumping and compressor stations in pipelines incl. auxiliaries - turbine driven — motor driven': { code: '04.6.3', fa: 'ایستگاه پمپاژ و تقویت فشار خطوط لوله با تجهیزات جانبی — محرک الکتروموتوری' },
  '04.6.4 Loading facilities but excluding off-shore facilities such as buoy moorings': { code: '04.6.4', fa: 'تأسیسات بارگیری، بدون تأسیسات فراساحلی مانند گویِ مهار' },
  '05.1 Basic metal extraction and processing - Direct reduction plants (Midrex) sponge iron production complete with all auxiliaries': { code: '05.1', fa: 'استخراج و فرآوری پایهٔ فلزات — واحد احیای مستقیم (میدرکس) و تولید آهن اسفنجی با تمام تجهیزات جانبی' },
  '05.1 Basic metal extraction and processing - Direct reduction plants (Midrex) sponge iron production complete with all auxiliaries — Blast f': { code: '05.1', fa: 'استخراج و فرآوری پایهٔ فلزات — کورهٔ بلند' },
  '05.2 Steel works — foundries, rolling mills and comparable processes (conversion of pig iron into steel)': { code: '05.2', fa: 'فولادسازی — ریخته‌گری، نورد و فرآیندهای مشابه (تبدیل چدن به فولاد)' },
  '05.3 Non-ferrous metal processing (aluminium, copper electrolysis, refining and comparable risks)': { code: '05.3', fa: 'فرآوری فلزات غیرآهنی (آلومینیوم، الکترولیز مس، پالایش و ریسک‌های مشابه)' },
  '05.4 Heavy engineering fabrication plants (shipyards, boiler shops, forges and comparable risks)': { code: '05.4', fa: 'کارخانه‌های ساخت سنگین (کشتی‌سازی، دیگ‌سازی، آهنگری و ریسک‌های مشابه)' },
  '05.5 Medium and light type of engineering (machine shops, metal fabrication, etc.)': { code: '05.5', fa: 'صنایع ساخت متوسط و سبک (ماشین‌کاری، ساخت قطعات فلزی و مانند آن)' },
  '05.6 Galvanising plants and comparable risks (surface finishing)': { code: '05.6', fa: 'واحد گالوانیزه و ریسک‌های مشابه (پوشش‌دهی سطح)' },
  '06.1 Quarries, gravel pits complete mainly comprising crushers, mills, conveyors, sorters and weighing installations, etc. but excluding mob': { code: '06.1', fa: 'معدن سنگ و شن، شامل سنگ‌شکن، آسیاب، نوار نقاله، سرند و توزین، بدون ماشین‌آلات متحرک' },
  '06.2 Cement, chalk and gypsum works — complete, excl. quarry installations': { code: '06.2', fa: 'کارخانهٔ سیمان، آهک و گچ — کامل، بدون تأسیسات معدن' },
  '06.3 Artificial stone works, brickyards, prefabricated building component works, ceramic works and comparable plants': { code: '06.3', fa: 'کارخانهٔ سنگ مصنوعی، آجرپزی، قطعات پیش‌ساختهٔ ساختمانی، سرامیک و مشابه' },
  '06.4 Glass works - Plate glass': { code: '06.4', fa: 'کارخانهٔ شیشه — شیشهٔ جام' },
  '06.4 Glass works - Other types': { code: '06.4', fa: 'کارخانهٔ شیشه — سایر انواع' },
  '07.1 Saw mills — incl. installations for seasoning of timber': { code: '07.1', fa: 'کارخانهٔ چوب‌بری — شامل تأسیسات خشک‌کردن چوب' },
  '07.2 Wood processing plants such as: Veneer, laminated board, plywood, wood chips board and comparable risks': { code: '07.2', fa: 'کارخانهٔ فرآوری چوب: روکش، نئوپان، تخته‌لایه، تخته‌خرده‌چوب و مشابه' },
  '07.3 Furniture factories and comparable plants': { code: '07.3', fa: 'کارخانهٔ مبلمان و واحدهای مشابه' },
  '08.1 Wood pulp and cellulose factories and comparable plants but excluding paper machine section': { code: '08.1', fa: 'کارخانهٔ خمیر چوب و سلولز و واحدهای مشابه، بدون بخش ماشین کاغذ' },
  '08.2 Paper and cardboard factories — incl. all auxiliaries, excl. pulp production facilities': { code: '08.2', fa: 'کارخانهٔ کاغذ و مقوا — با تمام تجهیزات جانبی، بدون واحد تولید خمیر' },
  '09.1 Printing shops and bookbinding shops (incl. newspaper printing; printing and packing material industries)': { code: '09.1', fa: 'چاپخانه و صحافی (شامل چاپ روزنامه؛ صنایع چاپ و بسته‌بندی)' },
  '09.2 Stationery factories and factories for paper and cardboard-packing material': { code: '09.2', fa: 'کارخانهٔ لوازم‌التحریر و بسته‌بندی کاغذی و مقوایی' },
  '10.1 Tanneries (leather industry)': { code: '10.1', fa: 'دباغی (صنعت چرم)' },
  '10.2 Leather goods factories (shoes, suitcases, bags, etc.)': { code: '10.2', fa: 'کارخانهٔ مصنوعات چرمی (کفش، چمدان، کیف و مانند آن)' },
  '11.1 Raw material processing plants (processing of wool, silk, flax, cotton and the like)': { code: '11.1', fa: 'واحد فرآوری مواد اولیه (پشم، ابریشم، کتان، پنبه و مانند آن)' },
  '11.2 Production of artificial fibres (feedstock, caprolactum, cellulose, etc.)': { code: '11.2', fa: 'تولید الیاف مصنوعی (خوراک اولیه، کاپرولاکتام، سلولز و مانند آن)' },
  '11.3 Textile fabrication (spinning, weaving, knitting mills)': { code: '11.3', fa: 'تولید منسوجات (ریسندگی، بافندگی، کشباف)' },
  '11.4 Finishing plants (dyeing, bleaching and printing processes)': { code: '11.4', fa: 'واحد تکمیل (رنگرزی، سفیدگری و چاپ پارچه)' },
  '11.5 Ready-made clothes factories': { code: '11.5', fa: 'کارخانهٔ پوشاک آماده' },
  '11.6 Textures for technical application (fabrication of carpets, linings, ropes, etc.)': { code: '11.6', fa: 'منسوجات با کاربرد صنعتی (فرش، آستری، طناب و مانند آن)' },
  '11.7 Industrial laundries, dry cleaners': { code: '11.7', fa: 'خشک‌شویی و لباس‌شویی صنعتی' },
  '12.1 Plastic & rubber products factories (mainly cutters, mills, mixers, extruders, plastic-blowing machines)': { code: '12.1', fa: 'کارخانهٔ محصولات پلاستیک و لاستیک (عمدتاً برش، آسیاب، میکسر، اکسترودر، دستگاه بادکن پلاستیک)' },
  '12.2 Tyre factories': { code: '12.2', fa: 'کارخانهٔ تایرسازی' },
  '12.3 Linoleum factories': { code: '12.3', fa: 'کارخانهٔ لینولئوم' },
  '12.4 Cable factories': { code: '12.4', fa: 'کارخانهٔ کابل‌سازی' },
  '12.5 Paint factories and processing of comparable products': { code: '12.5', fa: 'کارخانهٔ رنگ‌سازی و فرآوری محصولات مشابه' },
  '12.6 Production of pharmaceuticals and comparable plants': { code: '12.6', fa: 'تولید دارو و واحدهای مشابه' },
  '13.1 Grain & fodder mills, malthouses and comparable risks': { code: '13.1', fa: 'آسیاب غلات و خوراک دام، مالت‌سازی و ریسک‌های مشابه' },
  '13.2 Bakeries, biscuit and candy products factories': { code: '13.2', fa: 'نانوایی صنعتی، کارخانهٔ بیسکویت و شیرینی' },
  '13.3 Cocoa and chocolate factories': { code: '13.3', fa: 'کارخانهٔ کاکائو و شکلات' },
  '13.4 Breweries, distilleries, soft drinks factories': { code: '13.4', fa: 'کارخانهٔ آبجوسازی، تقطیر و نوشابه‌سازی' },
  '13.5 Tobacco processing plants': { code: '13.5', fa: 'کارخانهٔ فرآوری توتون و تنباکو' },
  '13.6 Edible oil factories - Solvent extraction': { code: '13.6', fa: 'کارخانهٔ روغن خوراکی — استخراج با حلال' },
  '13.6 Edible oil factories - Mechanical extraction': { code: '13.6', fa: 'کارخانهٔ روغن خوراکی — استخراج مکانیکی' },
  '13.7 Sugar factories but excluding power plant - Cane sugar': { code: '13.7', fa: 'کارخانهٔ قند و شکر، بدون نیروگاه — نیشکر' },
  '13.7 Sugar factories but excluding power plant - Beet sugar': { code: '13.7', fa: 'کارخانهٔ قند و شکر، بدون نیروگاه — چغندرقند' },
  '14.1 Dairies and comparable installations (ice-cream products; food industry, animal origin)': { code: '14.1', fa: 'کارخانهٔ لبنیات و واحدهای مشابه (بستنی؛ صنایع غذایی با منشأ دامی)' },
  '14.2 Slaughterhouses, meat processing factories, butcheries': { code: '14.2', fa: 'کشتارگاه، کارخانهٔ فرآوری گوشت و قصابی صنعتی' },
  '14.3 Fishmeal factories and comparable risks': { code: '14.3', fa: 'کارخانهٔ پودر ماهی و ریسک‌های مشابه' },
  '15.1 Canneries (meat, fish, vegetables)': { code: '15.1', fa: 'کارخانهٔ کنسروسازی (گوشت، ماهی، سبزیجات)' },
  '15.2 Cold stores (cold storage, deep freezing, controlled atmosphere; food refrigeration, canneries, cold stores)': { code: '15.2', fa: 'سردخانه (نگهداری سرد، انجماد عمیق، اتمسفر کنترل‌شده)' },
  '16.1 Cableways, skilifts and comparable installations': { code: '16.1', fa: 'تله‌کابین، تله‌اسکی و تأسیسات مشابه' },
  '16.2 Cranes, bridge cranes (transport systems, ports, warehouses)': { code: '16.2', fa: 'جرثقیل و جرثقیل سقفی (سامانه‌های حمل، بنادر، انبارها)' },
  '16.3 Lifts, hoists, lifting equipment, racks, conveying equipment, shelf-stackers and comparable installations': { code: '16.3', fa: 'آسانسور، بالابر، تجهیزات بالابری، قفسه‌بندی، تجهیزات انتقال و چیدمان قفسه' },
  '16.4 Tank farms incl. piping, pumps and measuring equipment but excluding civil works': { code: '16.4', fa: 'مخازن ذخیره شامل لوله‌کشی، پمپ و ابزار توزین، بدون کارهای عمرانی' },
  '17.1 Water treatment, water circulating, heating facilities for swimming pools': { code: '17.1', fa: 'تصفیه، گردش و گرمایش آب استخر شنا' },
  '17.2 Ice rinks complete including compressors but excluding civil works': { code: '17.2', fa: 'پیست یخ کامل شامل کمپرسور، بدون کارهای عمرانی' },
  '17.3 Floodlight installations and other facilities for sports stadiums (public services: stadiums, theatres, cinemas, entertainment)': { code: '17.3', fa: 'تأسیسات نورافکن و سایر تجهیزات ورزشگاه (خدمات عمومی: ورزشگاه، تئاتر، سینما)' },
  '18.1 General technical installations (heating, air conditioning, lifts, electrical and sanitary installations) — Hospitals, Hotels, Department Stores, Schools': { code: '18.1', fa: 'تأسیسات فنی عمومی (گرمایش، تهویهٔ مطبوع، آسانسور، تأسیسات برقی و بهداشتی) — بیمارستان، هتل، فروشگاه بزرگ، مدرسه' },
  '18.2 Medical and laboratory equipment, projection and photographic equipment — Hospitals, Hotels, Department Stores, Schools': { code: '18.2', fa: 'تجهیزات پزشکی و آزمایشگاهی، تجهیزات پروژکشن و عکاسی — بیمارستان، هتل، فروشگاه بزرگ، مدرسه' },
  '19.1 Irrigation systems complete (well installations with pumps, pivoting and/or fixed irrigation piping; excl. civil works and power plants)': { code: '19.1', fa: 'سامانهٔ آبیاری کامل (چاه با پمپ، لوله‌کشی آبیاری ثابت و دوّار؛ بدون کارهای عمرانی و نیروگاه)' },
  '19.2 General farm installations such as silos, storage tanks, packing and weighing machines, radio-communication equipment, maintenance shop': { code: '19.2', fa: 'تأسیسات عمومی مزرعه مانند سیلو، مخزن ذخیره، دستگاه بسته‌بندی و توزین، تجهیزات مخابراتی و کارگاه تعمیرات' },
  '19.3 Poultry farms (rearing hatcheries) and similar installations': { code: '19.3', fa: 'مرغداری (پرورش و جوجه‌کشی) و تأسیسات مشابه' },
}

/** Machine key → EAR code + Persian name. */
export const MACHINE_FA: Record<string, { code: string; fa: string }> = {
  '02.0.1 — Boiler feed pumps, incl. drive — turbine driven': { code: '02.0.1', fa: 'پمپ تغذیهٔ دیگ بخار با محرک — محرک توربینی' },
  '02.0.1 — Boiler feed pumps, incl. drive — motor driven': { code: '02.0.1', fa: 'پمپ تغذیهٔ دیگ بخار با محرک — محرک الکتروموتوری' },
  '02.0.2 — Heat exchangers, condensers': { code: '02.0.2', fa: 'مبدل حرارتی و کندانسور' },
  '02.0.3 — Electrical motors — asynchronous squirrel cage, up to 1 MW': { code: '02.0.3', fa: 'الکتروموتور — آسنکرون قفس‌سنجابی، تا ۱ مگاوات' },
  '02.0.3 — Electrical motors — asynchronous slip ring, up to 25 MW': { code: '02.0.3', fa: 'الکتروموتور — آسنکرون روتور سیم‌پیچی (اسلیپ‌رینگ)، تا ۲۵ مگاوات' },
  '02.0.3 — Electrical motors — synchronous, up to 25 MW': { code: '02.0.3', fa: 'الکتروموتور — سنکرون، تا ۲۵ مگاوات' },
  '02.0.3 — Electrical motors — direct current, up to 10 MW': { code: '02.0.3', fa: 'الکتروموتور — جریان مستقیم، تا ۱۰ مگاوات' },
  '02.0.3 — Electrical motors — special design (e.g. ring motor), up to 25 MW': { code: '02.0.3', fa: 'الکتروموتور — طرح خاص (مانند رینگ موتور)، تا ۲۵ مگاوات' },
  '02.0.4 — Transformers — single/three phase, up to 100 MW; 30 kV': { code: '02.0.4', fa: 'ترانسفورماتور — تک‌فاز/سه‌فاز، تا ۱۰۰ مگاوات؛ ۳۰ کیلوولت' },
  '02.0.4 — Transformers — special design (rectifier/furnace transformers), up to 50 MW': { code: '02.0.4', fa: 'ترانسفورماتور — طرح خاص (ترانسفورماتور یکسوساز/کوره)، تا ۵۰ مگاوات' },
  '02.0.5 — Pumps incl. motor drive — reciprocating type, up to 5 MW; 50 bar': { code: '02.0.5', fa: 'پمپ با الکتروموتور — نوع رفت‌وبرگشتی (پیستونی)، تا ۵ مگاوات؛ ۵۰ بار' },
  '02.0.5 — Pumps incl. motor drive — centrifugal type, up to 5 MW; 50 bar': { code: '02.0.5', fa: 'پمپ با الکتروموتور — نوع گریز از مرکز، تا ۵ مگاوات؛ ۵۰ بار' },
  '02.0.5 — Pumps incl. motor drive — special design (submerged, deepwell)': { code: '02.0.5', fa: 'پمپ با الکتروموتور — طرح خاص (شناور، چاه عمیق)' },
  '02.0.6 — Compressors incl. drive — reciprocating, up to 10 MW; 100 bar': { code: '02.0.6', fa: 'کمپرسور با محرک — رفت‌وبرگشتی (پیستونی)، تا ۱۰ مگاوات؛ ۱۰۰ بار' },
  '02.0.6 — Compressors — turbo (axial/radial), turbine driven, up to 10 MW; 50 bar': { code: '02.0.6', fa: 'کمپرسور — توربو (محوری/شعاعی)، محرک توربینی، تا ۱۰ مگاوات؛ ۵۰ بار' },
  '02.0.6 — Compressors — turbo (axial/radial), motor driven, up to 10 MW; 50 bar': { code: '02.0.6', fa: 'کمپرسور — توربو (محوری/شعاعی)، محرک الکتروموتوری، تا ۱۰ مگاوات؛ ۵۰ بار' },
  '02.0.7 — Fans, ventilators, up to 5 MW': { code: '02.0.7', fa: 'فن و هواکش، تا ۵ مگاوات' },
  '02.0.8 — Other individual machines, not specified elsewhere': { code: '02.0.8', fa: 'سایر ماشین‌آلات منفرد، طبقه‌بندی‌نشده (تأسیسات جانبی کارخانه)' },
  '03.0.1 — Dredgers, excavators, draglines and other exploitation machines': { code: '03.0.1', fa: 'لایروب، بیل مکانیکی، دراگلاین و سایر ماشین‌آلات استخراج' },
  '03.0.2 — Breakers, crushers': { code: '03.0.2', fa: 'سنگ‌شکن و خردکن' },
  '03.0.3 — Hoists, shaft lifts': { code: '03.0.3', fa: 'بالابر و آسانسور چاه معدن' },
  '03.0.4 — Compressors/ventilators incl. drive — turbine driven, up to 10 000 kW; 50 bar': { code: '03.0.4', fa: 'کمپرسور/هواکش با محرک — محرک توربینی، تا ۱۰٬۰۰۰ کیلووات؛ ۵۰ بار' },
  '03.0.4 — Compressors/ventilators incl. drive — motor driven, up to 10 000 kW; 50 bar': { code: '03.0.4', fa: 'کمپرسور/هواکش با محرک — محرک الکتروموتوری، تا ۱۰٬۰۰۰ کیلووات؛ ۵۰ بار' },
  '03.0.5 — Kilns, reverberatory furnaces, pelletizers': { code: '03.0.5', fa: 'کوره، کورهٔ شعله‌ای و دستگاه گندله‌سازی' },
  '03.0.6 — Other individual machines, not specified elsewhere': { code: '03.0.6', fa: 'سایر ماشین‌آلات منفرد، طبقه‌بندی‌نشده (صنعت معدن)' },
  '04.0.1 — Vessels, pressure vessels, distallation columns, crackers, reactors, furnaces': { code: '04.0.1', fa: 'مخزن، مخزن تحت فشار، برج تقطیر، کراکر، راکتور و کوره' },
  '04.0.2 — Turbo-compressors/pumps — turbine driven, ≤100 MW; ≤100 bar': { code: '04.0.2', fa: 'توربوکمپرسور/پمپ — محرک توربینی، تا ۱۰۰ مگاوات؛ تا ۱۰۰ بار' },
  '04.0.2 — Turbo-compressors/pumps — motor driven, ≤100 MW; ≤100 bar': { code: '04.0.2', fa: 'توربوکمپرسور/پمپ — محرک الکتروموتوری، تا ۱۰۰ مگاوات؛ تا ۱۰۰ بار' },
  '04.0.3 — Reciprocating type compressors and pumps — motor driven, ≤20 MW; ≤250 bar': { code: '04.0.3', fa: 'کمپرسور و پمپ رفت‌وبرگشتی — محرک الکتروموتوری، تا ۲۰ مگاوات؛ تا ۲۵۰ بار' },
  '04.0.4 — Centrifuges': { code: '04.0.4', fa: 'سانتریفیوژ' },
  '04.0.5 — Filters, cyclones, electrostatic precipitators': { code: '04.0.5', fa: 'فیلتر، سیکلون و رسوب‌دهندهٔ الکترواستاتیک' },
  '04.0.6 — Other individual machines, not specified elsewhere': { code: '04.0.6', fa: 'سایر ماشین‌آلات منفرد، طبقه‌بندی‌نشده (صنایع شیمیایی)' },
  '05.0.1 — Steel furnaces (Bessemer and Thomas converters, Siemens Martin furnaces)': { code: '05.0.1', fa: 'کورهٔ فولادسازی (کنورتور بسمر و توماس، کورهٔ زیمنس مارتین)' },
  '05.0.2 — Electrical arc furnaces': { code: '05.0.2', fa: 'کورهٔ قوس الکتریکی' },
  '05.0.3 — Other furnaces': { code: '05.0.3', fa: 'سایر کوره‌ها' },
  '05.0.4 — Hot rolling mills, continuous casting machines': { code: '05.0.4', fa: 'نورد گرم و ماشین ریخته‌گری پیوسته' },
  '05.0.5 — Extrusion presses, forging hammers, forging presses, shears and punching machines, presses, cutters': { code: '05.0.5', fa: 'پرس اکستروژن، چکش و پرس آهنگری، قیچی و پانچ، پرس و برشکار' },
  '05.0.6 — Cold rolling mills': { code: '05.0.6', fa: 'نورد سرد' },
  '05.0.7 — Machine tools, incl. NC equipment, lathes, planing etc.': { code: '05.0.7', fa: 'ماشین‌ابزار شامل تجهیزات کنترل عددی (CNC)، تراش، صفحه‌تراش و مانند آن' },
  '05.0.8 — Scrap shearing machines, shredders': { code: '05.0.8', fa: 'قیچی و خردکن ضایعات (شردر)' },
  '05.0.9 — Other individual machines, not specified elsewhere': { code: '05.0.9', fa: 'سایر ماشین‌آلات منفرد، طبقه‌بندی‌نشده (صنایع فلزی)' },
  '06.0.1 — Crushers (hammer, jaw)': { code: '06.0.1', fa: 'سنگ‌شکن (چکشی، فکی)' },
  '06.0.2 — Transport systems: conveyor belts, bucket elevators, air slides, air lifts': { code: '06.0.2', fa: 'سامانهٔ انتقال مواد: نوار نقاله، بالابر کاسه‌ای، ایرسلاید و ایرلیفت' },
  '06.0.3 — Mills: raw material grinding, clinker grinding, coal grinding, mixers': { code: '06.0.3', fa: 'آسیاب: آسیاب مواد خام، کلینکر و ذغال‌سنگ، و میکسر' },
  '06.0.4 — Filters: cyclones, separators, bag filters, electrostatic precipitators (mills, coolers)': { code: '06.0.4', fa: 'فیلتر: سیکلون، جداکننده، بگ‌فیلتر و رسوب‌دهندهٔ الکترواستاتیک (آسیاب و کولر)' },
  '06.0.5 — Kilns, precalcining and drying furnaces, reheating and melting furnaces': { code: '06.0.5', fa: 'کوره، کورهٔ پیش‌گرم و خشک‌کن، کورهٔ بازپخت و ذوب' },
  '06.0.6 — Coolers: rotary, planetary, grate type': { code: '06.0.6', fa: 'کولر: دوّار، سیاره‌ای و شبکه‌ای' },
  '06.0.7 — Material storage: stackers and reclaimers, weighing devices': { code: '06.0.7', fa: 'انبارش مواد: استکر و ریکلایمر، تجهیزات توزین' },
  '06.0.8 — Bagging machines, bulk loading': { code: '06.0.8', fa: 'دستگاه کیسه‌پرکن و بارگیری فله' },
  '06.0.9 — Glass manufacturing lines': { code: '06.0.9', fa: 'خط تولید شیشه' },
  '06.0.10 — Other individual machines, not specified elsewhere': { code: '06.0.10', fa: 'سایر ماشین‌آلات منفرد، طبقه‌بندی‌نشده (صنعت ساختمان)' },
  '07.0.1 — Frame saws': { code: '07.0.1', fa: 'ارهٔ نواری قاب‌دار' },
  '07.0.2 — Wood chippers, veneering machines, peelers, chippers etc.': { code: '07.0.2', fa: 'خردکن چوب، دستگاه روکش‌زنی، پوست‌کن و چیپرها' },
  '07.0.3 — Single and multi-stage presses': { code: '07.0.3', fa: 'پرس تک‌مرحله‌ای و چندمرحله‌ای' },
  '07.0.4 — Other individual machines, not specified elsewhere': { code: '07.0.4', fa: 'سایر ماشین‌آلات منفرد، طبقه‌بندی‌نشده (چوب و صنایع چوبی)' },
  '08.0.1 — Bark removing (decorticating) machines, wood chippers, wood grinders': { code: '08.0.1', fa: 'دستگاه پوست‌کنی چوب، خردکن و آسیاب چوب' },
  '08.0.2 — Beating mills, finishers, Jordan mills, Dolly tubs': { code: '08.0.2', fa: 'آسیاب خمیرکوبی، فینیشر، آسیاب جردن و مخزن دالی' },
  '08.0.3 — Pulp sheet or paper making machines': { code: '08.0.3', fa: 'ماشین تولید ورق خمیر یا کاغذ' },
  '08.0.4 — Black liquor boilers': { code: '08.0.4', fa: 'دیگ بخار مایع سیاه (بازیابی)' },
  '08.0.5 — Other individual machines, not specified elsewhere': { code: '08.0.5', fa: 'سایر ماشین‌آلات منفرد، طبقه‌بندی‌نشده (خمیر کاغذ و کاغذ)' },
  '09.0.1 — Rotary printing machines': { code: '09.0.1', fa: 'ماشین چاپ رتاتیو' },
  '09.0.2 — Other printing machines': { code: '09.0.2', fa: 'سایر ماشین‌های چاپ' },
  '09.0.3 — Type setting machines': { code: '09.0.3', fa: 'دستگاه حروف‌چینی' },
  '09.0.4 — Electronic scanning machines': { code: '09.0.4', fa: 'دستگاه اسکن الکترونیکی' },
  '09.0.5 — Presses, cutters, punchers': { code: '09.0.5', fa: 'پرس، برشکار و پانچ' },
  '09.0.6 — Other individual machines, not specified elsewhere': { code: '09.0.6', fa: 'سایر ماشین‌آلات منفرد، طبقه‌بندی‌نشده (چاپ و بسته‌بندی)' },
  '10.0.1 — All individual machines, not specified elsewhere': { code: '10.0.1', fa: 'تمام ماشین‌آلات منفرد، طبقه‌بندی‌نشده (صنعت چرم)' },
  '11.0.1 — Bale breakers, openers, carding machines': { code: '11.0.1', fa: 'بازکن عدل، بازکنندهٔ الیاف و ماشین حلاجی' },
  '11.0.2 — Spinning, roving, twisting machines': { code: '11.0.2', fa: 'ماشین ریسندگی، فتیله‌سازی و تابندگی' },
  '11.0.3 — Weaving machines, knitting machines': { code: '11.0.3', fa: 'ماشین بافندگی و کشباف' },
  '11.0.4 — Printing machines': { code: '11.0.4', fa: 'ماشین چاپ پارچه' },
  '11.0.5 — Washing machines (dry cleaners)': { code: '11.0.5', fa: 'ماشین شست‌وشو (خشک‌شویی)' },
  '11.0.6 — Other individual machines, not specified elsewhere': { code: '11.0.6', fa: 'سایر ماشین‌آلات منفرد، طبقه‌بندی‌نشده (صنعت نساجی)' },
  '12.0.1 — Extruders, injection moulding machines, plastic-blowing machines, vulcanizing presses': { code: '12.0.1', fa: 'اکسترودر، دستگاه تزریق پلاستیک، دستگاه بادکن پلاستیک و پرس ولکانیزاسیون' },
  '12.0.2 — Cutters, mills, mixers, calanders': { code: '12.0.2', fa: 'برشکار، آسیاب، میکسر و کالندر' },
  '12.0.3 — Strand-bead forming machines': { code: '12.0.3', fa: 'دستگاه شکل‌دهی طوقهٔ تایر' },
  '12.0.4 — Vacuum impregnation machines': { code: '12.0.4', fa: 'دستگاه اشباع خلأ' },
  '12.0.5 — Other individual machines, not specified elsewhere': { code: '12.0.5', fa: 'سایر ماشین‌آلات منفرد، طبقه‌بندی‌نشده (پلاستیک و لاستیک)' },
  '13.0.1 — Aspirators, cleaning, screening, brushing, shelling, winnowing machines': { code: '13.0.1', fa: 'دستگاه مکنده، بوجاری، سرند، برس‌زنی، پوست‌کنی و باددهی غلات' },
  '13.0.2 — Cyclones, filters, dust collectors, bag filters etc.': { code: '13.0.2', fa: 'سیکلون، فیلتر، غبارگیر و بگ‌فیلتر' },
  '13.0.3 — Ball mills, grinders, crushing mills': { code: '13.0.3', fa: 'آسیاب گلوله‌ای، آسیاب و آسیاب خردکن' },
  '13.0.4 — Oil presses, cocoa butter presses, other presses, beet slicers, cutters, extractors, pelletizers': { code: '13.0.4', fa: 'پرس روغن‌گیری، پرس کرهٔ کاکائو، سایر پرس‌ها، خلال‌کن چغندر، برشکار، استخراج‌کننده و گندله‌ساز' },
  '13.0.5 — Sugar cane crusher mills (roller mills) incl. drive — turbine driven, up to 5 MW': { code: '13.0.5', fa: 'آسیاب غلتکی نیشکر با محرک — محرک توربینی، تا ۵ مگاوات' },
  '13.0.5 — Sugar cane crusher mills (roller mills) incl. drive — motor driven, up to 5 MW': { code: '13.0.5', fa: 'آسیاب غلتکی نیشکر با محرک — محرک الکتروموتوری، تا ۵ مگاوات' },
  '13.0.6 — Ovens, roasting plants, dryers': { code: '13.0.6', fa: 'کوره، دستگاه بوداده‌کردن و خشک‌کن' },
  '13.0.7 — Bottle cleaning and filling machines, packing machines': { code: '13.0.7', fa: 'دستگاه شست‌وشو و پرکن بطری و دستگاه بسته‌بندی' },
  '13.0.8 — Centrifuges, separators': { code: '13.0.8', fa: 'سانتریفیوژ و جداکننده' },
  '13.0.9 — Automatic cigar and cigarette production machines': { code: '13.0.9', fa: 'دستگاه خودکار تولید سیگار و سیگار برگ' },
  '13.0.10 — Vacuum dryers, pulverizer installations for instant pulverized food production': { code: '13.0.10', fa: 'خشک‌کن خلأ و تأسیسات پودرسازی برای تولید مواد غذایی فوری' },
  '13.0.11 — Other individual machines, not specified elsewhere': { code: '13.0.11', fa: 'سایر ماشین‌آلات منفرد، طبقه‌بندی‌نشده (صنایع غذایی گیاهی)' },
  '14.0.1 — Heaters, pasteurizers, homogenizers, coolers': { code: '14.0.1', fa: 'گرم‌کن، پاستوریزاتور، هموژنایزر و کولر' },
  '14.0.2 — Cooling compressors incl. motor drive': { code: '14.0.2', fa: 'کمپرسور برودتی با الکتروموتور' },
  '14.0.3 — Centrifuges, separators': { code: '14.0.3', fa: 'سانتریفیوژ و جداکننده' },
  '14.0.4 — Meat saws, cutters, choppers, mincing machines, mixers': { code: '14.0.4', fa: 'ارهٔ گوشت، برشکار، خردکن، چرخ گوشت و میکسر' },
  '14.0.5 — Vacuum dryers, pulverizers': { code: '14.0.5', fa: 'خشک‌کن خلأ و پودرکن' },
  '14.0.6 — Bottle cleaning and filling machines, packing machines': { code: '14.0.6', fa: 'دستگاه شست‌وشو و پرکن بطری و دستگاه بسته‌بندی' },
  '14.0.7 — Other individual machines, not specified elsewhere': { code: '14.0.7', fa: 'سایر ماشین‌آلات منفرد، طبقه‌بندی‌نشده (صنایع غذایی دامی)' },
  '15.0.1 — Cooling compressors incl. motor drive': { code: '15.0.1', fa: 'کمپرسور برودتی با الکتروموتور' },
  '15.0.2 — Fans, blowers': { code: '15.0.2', fa: 'فن و دمنده' },
  '15.0.3 — Evaporators, coolers, heat exchangers': { code: '15.0.3', fa: 'اواپراتور، کولر و مبدل حرارتی' },
  '15.0.4 — Autoclaves, sterilizers': { code: '15.0.4', fa: 'اتوکلاو و استریلایزر' },
  '15.0.5 — Can manufacturing machines, filling, sealing, labelling machines': { code: '15.0.5', fa: 'دستگاه قوطی‌سازی، پرکن، دربندی و برچسب‌زنی' },
  '15.0.6 — Other individual machines, not specified elsewhere': { code: '15.0.6', fa: 'سایر ماشین‌آلات منفرد، طبقه‌بندی‌نشده (سردخانه و صنایع برودتی)' },
  '18.0.1 — Air conditioning devices — window units': { code: '18.0.1', fa: 'تجهیزات تهویهٔ مطبوع — کولر پنجره‌ای' },
  '18.0.1 — Air conditioning devices — compressors, pumps, vaporizers, ozonizers': { code: '18.0.1', fa: 'تجهیزات تهویهٔ مطبوع — کمپرسور، پمپ، اواپراتور و ازن‌ساز' },
  '18.0.2 — Boilers for warm water and heating': { code: '18.0.2', fa: 'دیگ آب گرم و گرمایش' },
  '18.0.3 — Lifts, escalators': { code: '18.0.3', fa: 'آسانسور و پله‌برقی' },
  '18.0.4 — Other individual machines, not specified elsewhere': { code: '18.0.4', fa: 'سایر ماشین‌آلات منفرد، طبقه‌بندی‌نشده (بیمارستان و هتل)' },
}

/** Display label for a sub-group, falling back to the English name. */
export function subGroupLabel(name: string): string {
  const t = SUBGROUP_FA[name]
  return t ? withCode(t.code, t.fa) : name
}

/** Display label for a machine, falling back to the English key. */
export function machineLabel(key: string): string {
  const t = MACHINE_FA[key]
  return t ? withCode(t.code, t.fa) : key
}
